sonar.projectKey=LMS-Maintenance-Project
sonar.projectName=LMS Maintenance Project
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.java.binaries=target/classes

# Authentication (use your token)
sonar.host.url=http://localhost:9000
sonar.login=squ_93e87617089a1fc41cf7b7bf8f93057ffd021750

